"""Add exchange rates table

Revision ID: 11afbcb35cef
Revises: 6415f3c4d023
Create Date: 2026-06-27 21:04:58.251065

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "11afbcb35cef"
down_revision: str | None = "6415f3c4d023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exchange_rates_currency"), "exchange_rates", ["currency"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exchange_rates_currency"), table_name="exchange_rates")
    op.drop_table("exchange_rates")
    # ### end Alembic commands ###
