"""create employees and salaries

Revision ID: 14fa80ce73f7
Revises:
Create Date: 2026-06-26 18:57:18.024807

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "14fa80ce73f7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_email"), "employees", ["email"], unique=True)
    op.create_index(op.f("ix_employees_is_active"), "employees", ["is_active"], unique=False)
    op.create_table(
        "salaries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("salary", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("salary_usd", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_salaries_employee_id_valid_to", "salaries", ["employee_id", "valid_to"], unique=False
    )
    op.execute("""
    CREATE VIEW active_employees AS
    SELECT
        e.id, e.first_name, e.last_name, e.email,
        e.department, e.country, e.is_active,
        e.created_at, e.updated_at,
        sh.salary, sh.currency, sh.salary_usd,
        sh.valid_from
    FROM employees e
    JOIN salaries sh
        ON sh.employee_id = e.id
        AND sh.valid_to IS NULL
    WHERE e.is_active = 1
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS active_employees")
    op.drop_index("ix_salaries_employee_id_valid_to", table_name="salaries")
    op.drop_table("salaries")
    op.drop_index(op.f("ix_employees_is_active"), table_name="employees")
    op.drop_index(op.f("ix_employees_email"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
