"""remove unique constraint from exchange_rates currency

Revision ID: 63bf49e0df82
Revises: a1b2c3d4e5f6
Create Date: 2026-06-28 22:39:33.070888

"""

from collections.abc import Sequence

from alembic import op

revision: str = "63bf49e0df82"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exchange_rates_currency"), table_name="exchange_rates")
    op.create_index(
        op.f("ix_exchange_rates_currency"), "exchange_rates", ["currency"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exchange_rates_currency"), table_name="exchange_rates")
    op.create_index(op.f("ix_exchange_rates_currency"), "exchange_rates", ["currency"], unique=True)
    # ### end Alembic commands ###
