"""link salary to exchange_rate

Revision ID: 866ab64c33a7
Revises: 2235566c3b40
Create Date: 2026-06-27 21:49:09.059039

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "866ab64c33a7"
down_revision: str | None = "2235566c3b40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS active_employees")
    with op.batch_alter_table("salaries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("exchange_rate_id", sa.Integer(), nullable=False, server_default="1")
        )
        batch_op.create_foreign_key(
            "fk_salaries_exchange_rate_id_exchange_rates",
            "exchange_rates",
            ["exchange_rate_id"],
            ["id"],
        )

    op.execute("""
    CREATE VIEW active_employees AS
    SELECT
        e.id,
        e.first_name,
        e.last_name,
        e.email,
        e.department,
        e.country,
        s.salary_minor_units,
        s.currency,
        s.salary_usd_minor_units,
        s.valid_from,
        e.created_at,
        e.updated_at
    FROM employees e
    JOIN salaries s ON e.id = s.employee_id
    WHERE e.is_active = TRUE AND s.valid_to IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS active_employees")
    with op.batch_alter_table("salaries", schema=None) as batch_op:
        batch_op.drop_constraint("fk_salaries_exchange_rate_id_exchange_rates", type_="foreignkey")
        batch_op.drop_column("exchange_rate_id")

    op.execute("""
    CREATE VIEW active_employees AS
    SELECT
        e.id,
        e.first_name,
        e.last_name,
        e.email,
        e.department,
        e.country,
        s.salary_minor_units,
        s.currency,
        s.salary_usd_minor_units,
        s.valid_from,
        e.created_at,
        e.updated_at
    FROM employees e
    JOIN salaries s ON e.id = s.employee_id
    WHERE e.is_active = TRUE AND s.valid_to IS NULL
    """)
    # ### end Alembic commands ###
