"""add salary components

Revision ID: 88f5d5a9b165
Revises: 811e0e1f0e77
Create Date: 2026-06-28 02:06:33.301666

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "88f5d5a9b165"
down_revision: str | None = "811e0e1f0e77"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("salaries", "salary_minor_units", new_column_name="base_salary_minor_units")
    op.add_column(
        "salaries", sa.Column("housing_allowance_minor_units", sa.Integer(), nullable=True)
    )
    op.add_column("salaries", sa.Column("equity_minor_units", sa.Integer(), nullable=True))
    op.add_column("salaries", sa.Column("other_allowance_minor_units", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("salaries", "base_salary_minor_units", new_column_name="salary_minor_units")
    op.drop_column("salaries", "other_allowance_minor_units")
    op.drop_column("salaries", "equity_minor_units")
    op.drop_column("salaries", "housing_allowance_minor_units")
    # ### end Alembic commands ###
