"""simplify_exchange_rates

Revision ID: bbdf94b108a3
Revises: 5c804d16e310
Create Date: 2026-06-28 23:28:27.601199

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "bbdf94b108a3"
down_revision: str | None = "5c804d16e310"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS active_employees")
    op.execute("DELETE FROM exchange_rates WHERE valid_to IS NOT NULL")
    op.drop_index(op.f("ix_exchange_rates_currency"), table_name="exchange_rates")
    op.create_index(op.f("ix_exchange_rates_currency"), "exchange_rates", ["currency"], unique=True)
    op.drop_column("exchange_rates", "valid_to")
    op.drop_column("exchange_rates", "valid_from")

    op.execute("""
        CREATE VIEW active_employees AS
        SELECT
            e.id,
            e.first_name,
            e.last_name,
            e.email,
            e.department_id,
            d.name AS department_name,
            e.country_id,
            c.code AS country_code,
            c.name AS country_name,
            c.default_currency_id AS country_default_currency_id,
            ccurr.code AS country_default_currency_code,
            ccurr.name AS country_default_currency_name,
            s.base_salary_minor_units,
            s.housing_allowance_minor_units,
            s.equity_minor_units,
            s.other_allowance_minor_units,
            s.base_salary_minor_units + 
                COALESCE(s.housing_allowance_minor_units, 0) + 
                COALESCE(s.equity_minor_units, 0) + 
                COALESCE(s.other_allowance_minor_units, 0) AS salary_minor_units,
            s.currency_id,
            curr.code AS currency_code,
            curr.name AS currency_name,
            CASE 
                WHEN curr.code = 'USD' THEN 
                    (s.base_salary_minor_units + COALESCE(s.housing_allowance_minor_units, 0) + COALESCE(s.equity_minor_units, 0) + COALESCE(s.other_allowance_minor_units, 0))
                WHEN er.rate IS NOT NULL THEN
                    CAST(
                        (s.base_salary_minor_units + 
                        COALESCE(s.housing_allowance_minor_units, 0) + 
                        COALESCE(s.equity_minor_units, 0) + 
                        COALESCE(s.other_allowance_minor_units, 0)) / er.rate
                    AS INTEGER)
                ELSE NULL
            END AS salary_usd_minor_units,
            s.valid_from,
            e.created_at,
            e.updated_at
        FROM employees e
        LEFT JOIN departments d ON e.department_id = d.id
        LEFT JOIN countries c ON e.country_id = c.id
        LEFT JOIN currencies ccurr ON c.default_currency_id = ccurr.id
        LEFT JOIN salaries s ON e.id = s.employee_id AND s.valid_to IS NULL
        LEFT JOIN currencies curr ON s.currency_id = curr.id
        LEFT JOIN exchange_rates er ON curr.code = er.currency 
            AND curr.code != 'USD'
        WHERE e.is_active = TRUE
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "exchange_rates", sa.Column("valid_from", sa.DATE(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "exchange_rates", sa.Column("valid_to", sa.DATE(), autoincrement=False, nullable=True)
    )
    op.execute("UPDATE exchange_rates SET valid_from = '2020-01-01'")
    op.alter_column("exchange_rates", "valid_from", nullable=False)
    op.drop_index(op.f("ix_exchange_rates_currency"), table_name="exchange_rates")
    op.create_index(
        op.f("ix_exchange_rates_currency"), "exchange_rates", ["currency"], unique=False
    )

    op.execute("DROP VIEW IF EXISTS active_employees")
    op.execute("""
        CREATE VIEW active_employees AS
        SELECT
            e.id,
            e.first_name,
            e.last_name,
            e.email,
            e.department_id,
            d.name AS department_name,
            e.country_id,
            c.code AS country_code,
            c.name AS country_name,
            c.default_currency_id AS country_default_currency_id,
            ccurr.code AS country_default_currency_code,
            ccurr.name AS country_default_currency_name,
            s.base_salary_minor_units,
            s.housing_allowance_minor_units,
            s.equity_minor_units,
            s.other_allowance_minor_units,
            s.base_salary_minor_units + 
                COALESCE(s.housing_allowance_minor_units, 0) + 
                COALESCE(s.equity_minor_units, 0) + 
                COALESCE(s.other_allowance_minor_units, 0) AS salary_minor_units,
            s.currency_id,
            curr.code AS currency_code,
            curr.name AS currency_name,
            CASE 
                WHEN curr.code = 'USD' THEN 
                    (s.base_salary_minor_units + COALESCE(s.housing_allowance_minor_units, 0) + COALESCE(s.equity_minor_units, 0) + COALESCE(s.other_allowance_minor_units, 0))
                WHEN er.rate IS NOT NULL THEN
                    CAST(
                        (s.base_salary_minor_units + 
                        COALESCE(s.housing_allowance_minor_units, 0) + 
                        COALESCE(s.equity_minor_units, 0) + 
                        COALESCE(s.other_allowance_minor_units, 0)) / er.rate
                    AS INTEGER)
                ELSE NULL
            END AS salary_usd_minor_units,
            s.valid_from,
            e.created_at,
            e.updated_at
        FROM employees e
        LEFT JOIN departments d ON e.department_id = d.id
        LEFT JOIN countries c ON e.country_id = c.id
        LEFT JOIN currencies ccurr ON c.default_currency_id = ccurr.id
        LEFT JOIN salaries s ON e.id = s.employee_id AND s.valid_to IS NULL
        LEFT JOIN currencies curr ON s.currency_id = curr.id
        LEFT JOIN exchange_rates er ON curr.code = er.currency 
            AND er.valid_to IS NULL 
            AND curr.code != 'USD'
        WHERE e.is_active = TRUE
    """)
    # ### end Alembic commands ###
