"""add_active_salary_unique_index

Revision ID: d86347c9d7ad
Revises: c04f90b580e5
Create Date: 2026-07-01 03:15:43.967946

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d86347c9d7ad"
down_revision: str | None = "c04f90b580e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("DROP VIEW IF EXISTS active_employees")
    with op.batch_alter_table("employees") as batch_op:
        batch_op.alter_column("department_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("country_id", existing_type=sa.INTEGER(), nullable=False)
    with op.batch_alter_table("salaries") as batch_op:
        batch_op.alter_column("currency_id", existing_type=sa.INTEGER(), nullable=False)

    op.create_index(
        "ix_active_salary",
        "salaries",
        ["employee_id"],
        unique=True,
        sqlite_where=sa.text("valid_to IS NULL"),
        postgresql_where=sa.text("valid_to IS NULL"),
    )

    op.execute("""
        CREATE VIEW active_employees AS
        SELECT
            e.id,
            e.first_name,
            e.last_name,
            e.email,
            e.department_id,
            d.name AS department_name,
            e.country_id,
            c.code AS country_code,
            c.name AS country_name,
            c.default_currency_id AS country_default_currency_id,
            ccurr.code AS country_default_currency_code,
            ccurr.name AS country_default_currency_name,
            s.base_salary_minor_units,
            s.housing_allowance_minor_units,
            s.equity_minor_units,
            s.other_allowance_minor_units,
            s.base_salary_minor_units +
                COALESCE(s.housing_allowance_minor_units, 0) +
                COALESCE(s.equity_minor_units, 0) +
                COALESCE(s.other_allowance_minor_units, 0) AS salary_minor_units,
            s.currency_id,
            curr.code AS currency_code,
            curr.name AS currency_name,
            CASE
                WHEN curr.code = 'USD' THEN
                    (s.base_salary_minor_units +
                    COALESCE(s.housing_allowance_minor_units, 0) +
                    COALESCE(s.equity_minor_units, 0) +
                    COALESCE(s.other_allowance_minor_units, 0))
                WHEN er.rate IS NOT NULL THEN
                    CAST(
                        (s.base_salary_minor_units +
                        COALESCE(s.housing_allowance_minor_units, 0) +
                        COALESCE(s.equity_minor_units, 0) +
                        COALESCE(s.other_allowance_minor_units, 0)) * er.rate
                    AS INTEGER)
                ELSE NULL
            END AS salary_usd_minor_units,
            s.valid_from,
            e.created_at,
            e.updated_at
        FROM employees e
        LEFT JOIN departments d ON e.department_id = d.id
        LEFT JOIN countries c ON e.country_id = c.id
        LEFT JOIN currencies ccurr ON c.default_currency_id = ccurr.id
        LEFT JOIN salaries s ON e.id = s.employee_id AND s.valid_to IS NULL
        LEFT JOIN currencies curr ON s.currency_id = curr.id
        LEFT JOIN exchange_rates er ON curr.code = er.currency
            AND curr.code != 'USD'
        WHERE e.is_active = TRUE
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_active_salary",
        table_name="salaries",
        sqlite_where=sa.text("valid_to IS NULL"),
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    with op.batch_alter_table("salaries") as batch_op:
        batch_op.alter_column("currency_id", existing_type=sa.INTEGER(), nullable=True)
    with op.batch_alter_table("employees") as batch_op:
        batch_op.alter_column("country_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("department_id", existing_type=sa.INTEGER(), nullable=True)

    op.execute("""
        CREATE VIEW active_employees AS
        SELECT
            e.id,
            e.first_name,
            e.last_name,
            e.email,
            e.department_id,
            d.name AS department_name,
            e.country_id,
            c.code AS country_code,
            c.name AS country_name,
            c.default_currency_id AS country_default_currency_id,
            ccurr.code AS country_default_currency_code,
            ccurr.name AS country_default_currency_name,
            s.base_salary_minor_units,
            s.housing_allowance_minor_units,
            s.equity_minor_units,
            s.other_allowance_minor_units,
            s.base_salary_minor_units +
                COALESCE(s.housing_allowance_minor_units, 0) +
                COALESCE(s.equity_minor_units, 0) +
                COALESCE(s.other_allowance_minor_units, 0) AS salary_minor_units,
            s.currency_id,
            curr.code AS currency_code,
            curr.name AS currency_name,
            CASE
                WHEN curr.code = 'USD' THEN
                    (s.base_salary_minor_units +
                    COALESCE(s.housing_allowance_minor_units, 0) +
                    COALESCE(s.equity_minor_units, 0) +
                    COALESCE(s.other_allowance_minor_units, 0))
                WHEN er.rate IS NOT NULL THEN
                    CAST(
                        (s.base_salary_minor_units +
                        COALESCE(s.housing_allowance_minor_units, 0) +
                        COALESCE(s.equity_minor_units, 0) +
                        COALESCE(s.other_allowance_minor_units, 0)) * er.rate
                    AS INTEGER)
                ELSE NULL
            END AS salary_usd_minor_units,
            s.valid_from,
            e.created_at,
            e.updated_at
        FROM employees e
        LEFT JOIN departments d ON e.department_id = d.id
        LEFT JOIN countries c ON e.country_id = c.id
        LEFT JOIN currencies ccurr ON c.default_currency_id = ccurr.id
        LEFT JOIN salaries s ON e.id = s.employee_id AND s.valid_to IS NULL
        LEFT JOIN currencies curr ON s.currency_id = curr.id
        LEFT JOIN exchange_rates er ON curr.code = er.currency
            AND curr.code != 'USD'
        WHERE e.is_active = TRUE
    """)
    # ### end Alembic commands ###
