"""add_active_salary_unique_index

Revision ID: d86347c9d7ad
Revises: c04f90b580e5
Create Date: 2026-07-01 03:15:43.967946

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d86347c9d7ad"
down_revision: str | None = "c04f90b580e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("employees", "department_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("employees", "country_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("salaries", "currency_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(
        "ix_active_salary",
        "salaries",
        ["employee_id"],
        unique=True,
        sqlite_where=sa.text("valid_to IS NULL"),
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_active_salary",
        table_name="salaries",
        sqlite_where=sa.text("valid_to IS NULL"),
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.alter_column("salaries", "currency_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("employees", "country_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("employees", "department_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
